#!/usr/bin/env bash
# Installs Nginx

sudo apt-get update
sudo apt-get install -y nginx

sudo echo "Hello World" > /var/www/html/index.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudp service nginx restart
