#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get install -y haproxy

# Configure HAProxy
echo '
frontend www-http
        bind *:80
        mode http
        default_backend www-backend
backend www-backend
        balance roundrobin
	server 483184-web-01 52.87.234.190:80 check
        server 483184-web-02 54.160.87.111:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart