#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server

# Install HAProxy
sudo apt-get update -y
sudo apt-get install haproxy -y

# Configure HAProxy
config=\
"frontend test80
        bind *:80
        mode http
        default_backend back80

backend back80
        server web-01 52.87.234.190:80 check
        server web-02 54.160.87.111:80 check
        balance roundrobin
"

sudo echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Start HAProxy
sudo service haproxy start
