#!/usr/bin/env bash
# run nginx as nginx
service nginx stop

# replace the default user with nginx
sed -i "s/user www-data/user nginx" /etc/nginx/nginx.conf

sed -i "s/80/8080/g" /etc/nginx/sites-available/default

sudo -u nginx service nginx start
